- name: setting /etc/iptables.test.rules
  copy: src=iptables.rules
    dest=/etc/iptables.test.rules
    owner=0 group=0 mode=644

- name: setting /etc/network/if-pre-up.d/iptables
  copy: src=iptables
    dest=/etc/network/if-pre-up.d/
    owner=0 group=0 mode=755

- name: Setting iptables
  shell: iptables-restore < /etc/iptables.test.rules

- name: Save iptables
  shell: iptables-save > /etc/iptables.up.rules
