- name: Install docker dependencies
  apt:  
    update_cache: yes
    pkg:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg2 
      - software-properties-common


- name: Add official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present


- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ debian_version_code }} stable"
    state: present


- name: Install docker-ce
  apt:
    update_cache: yes
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 


- name: Install docker pip packages
  pip: name=docker executable=pip3

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/bin/docker-compose
    mode: 0755

    #- name: Disable upgrade 
    #  shell: 'sudo apt-mark hold docker-ce'
